
# type: ignore

from setuptools import setup, find_packages

requirements = [
"aiohappyeyeballs==2.6.1",
"aiohttp==3.12.15",
"aiosignal==1.4.0",
"attrs==25.3.0",
"cachetools==5.5.2",
"certifi==2025.8.3",
"charset-normalizer==3.4.3",
"dotenv==0.9.9",
"frozenlist==1.7.0",
"google-api-core==2.25.1",
"google-auth==2.40.3",
"google-cloud-bigquery==3.38.0",
"google-cloud-core==2.4.3",
"google-crc32c==1.7.1",
"google-resumable-media==2.7.2",
"googleapis-common-protos==1.70.0",
"grpcio==1.75.0",
"grpcio-status==1.75.0",
"idna==3.10",
"multidict==6.6.4",
"numpy==2.3.3",
"packaging==25.0",
"pandas==2.3.2",
"propcache==0.3.2",
"proto-plus==1.26.1",
"protobuf==6.32.1",
"pyasn1==0.6.1",
"pyasn1_modules==0.4.2",
"python-dateutil==2.9.0.post0",
"python-dotenv==1.1.1",
"pytz==2025.2",
"requests==2.32.5",
"rsa==4.9.1",
"six==1.17.0",
"typing_extensions==4.15.0",
"tzdata==2025.2",
"urllib3==2.5.0",
"yarl==1.20.1",
]

setup(
    name="data_quality_monitoring",
    version="0.1.0",
    author="Younes Essoualhi",
    author_email="younesessoualhi@gmail.com",
    description="description",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=find_packages(),
    install_requires=requirements,
    python_requires=">=3.8",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    include_package_data=True,
    package_data={"data_quality_monitoring": ["py.typed"]},
)