data_quality_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('host') }}"
      user: "{{ env_var('user') }}"
      password: "{{ env_var('password') }}"
      port: "{{ env_var('port') | as_number }}"
      dbname: "{{ env_var('dbname') }}"
      schema: public
      threads: 4
      keepalives_idle: 0

    bigquery_dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('key') }}"
      project: "{{ env_var('project_id') }}"
      dataset: "{{ env_var('dataset_id') }}"
      table: "{{ env_var('table_id') }}"      
      threads: 4